--- #YAML:1.0
name:                Puzzle
version:             0.07
abstract:            A Web framework 
license:             gpl2
author:              
    - Emiliano Bruni <info@ebruni.it>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Apache2::Cookie:               0
    Apache::DBI:                   0
    Apache::Session::MySQL:        0
    Class::Container:              0
    Data::Dumper:                  0
    DBIx::Class::Schema:           0
    DBIx::Class::Schema::Loader:   0
    File::Spec:                    0
    HTML::Entities:                0
    HTML::Mason:                   0
    HTML::Template::Pro::Extension: 0
    I18N::AcceptLanguage:          0
    JSON::Any:                     0
    Mail::Sendmail:                0
    mod_perl2:                     1.999022
    Params::Validate:              0
    Time::HiRes:                   0
    XML::Simple:                   0
    YAML:                          0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
